---
url:
  description: "URL of the nexus3 instance (e.g. ``http://localhost:8081``)"
  type: "string"
  secret: false
  required: true
  position: 0
verify:
  description: "verify TLS, only used if the ``url`` option specifies an ``HTTPS`` connection"
  type: boolean
  position: 1
  default: True
user:
  description: "Username"
  type: "string"
  secret: false
  required: false
  position: 2
password:
  description: "Password"
  type: "string"
  secret: true
  required: false
  position: 3
profiles:
  description: "Nexus3 Connection profile name. This will use above options as"
  type: object
  required: false
  properties: {}
  additionalProperties:
    type: object
    additionalProperties: false
    properties:
      url:
        description: "URL of the JIRA instance (e.g. ``https://myproject.atlassian.net``)"
        type: "string"
        secret: false
        required: true
      verify:
        description: "verify TLS, only used if the ``url`` option specifies an ``HTTPS`` connection"
        type: boolean
        default: True
      user:
        description: "Username"
        type: "string"
        secret: false
        required: false
      password:
        description: "Password"
        type: "string"
        secret: true
        required: false
